#pragma once

enum class SYSTEM_STATE {
    IDLE = 0,
    MOVE = 1,
    ERROR
};

enum class SYSTEM_MODE {
    CLEAR = 0,
    PWM_TEST = 3,
    CURRENT_TEST = 4,
    SPEED_TEST = 5,
    LONG_TERM_TEST = 6,
    REFERENCE = 7,
    NORMAL = 8
};

enum class ERROR_CODE {
    NO_ERROR = 0,
    NON_VOLATILE_MEMORY_INITIALIZATION_ERROR = 1,
    NON_VOLATILE_MEMORY_WRITE_ERROR = 2,
    NON_VOLATILE_MEMORY_READ_ERROR = 3,
    GENERIC_NON_VOLATILE_MEMORY_ERROR = 4,
    COLLISION_EVENT = 5,
    STOP_OVERCURRENT_ERROR = 6,
    ERROR_OVERCURRENT_ERROR = 7,
    HARDWARE_FAULT_OVERCURRENT_ERROR = 8,
    I2T_ERROR = 9,
    POWER_SUPPLY_I2T_ERROR = 10,
    POWER_SUPPLY_OVERTEMPERATURE_ERROR = 11,
    MOTOR_DRIVE_OVERTEMPERATURE_ERROR = 12,
    M3_MOTOR_DRIVE_OVERTEMPERATURE_ERROR = 13,
    POSITION_ERROR = 14,
    MOTOR_BLOCKED_ERROR = 15,
    MOTOR_PRESENCE_ERROR = 16,
    POWER_SUPPLY_OVERLOAD_ERROR = 17,
    HARDWARE_ERROR = 18,
    MOTOR_SEQUENCE_ERROR = 19,
    SAFETY_ADAPTER_MISSING = 20,
    SAFETY_ADAPTER_ACTIVE = 21,
    HALL_SENSOR_ERROR = 22,
    HUB_CONTROLLER_CONFIG_ERROR = 23,
    HUB_CONTROLLER_COUNT_ERROR = 24,
    BATTERY_OVERCURRENT = 25,
    BATTERY_SHORTCIRCUIT = 26,
    BATTERY_OVERVOLTAGE = 27,
    BATTERY_UNDERVOLTAGE = 28,
    BATTERY_DEVICEFAULT = 29,
    BATTERY_LOWPOWER = 30,
    BATTERY_TEMP = 31,
    HUB_FIRMWARE_ERROR = 32
};

enum class REFERENCE_MODE_STATE {
    RM_IDLE = 0,
    RM_PRE_POSITION = 1,
    RM_FINAL_POSITION = 2,
    RM_FINAL_POSITION_RUN = 3,
    RM_REACHED = 4,
};

enum class USER_POSITION {
    POS_1 = 1,
    POS_2 = 2,
    POS_3 = 3,
    POS_4 = 4
};
