name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Conan
        run: pip3 install conan

      - name: Create Conan profile
        run: conan profile detect

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Package with CPack
        run: cmake --build build --config Release --target package

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: build/packages/*.exe